Repository Libra-foundation/python-template, pull requests merged in 2023-01, with the labels that each got.

#4 Mypy
  poetry.lock
  pyproject.toml
  src/keep_it.py
Labels: enhancement

#5 Bandit
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  requirements-dev.txt
Labels: enhancement

#6 [FEATURE] PyLint configuration
  poetry.lock
  pyproject.toml
  requirements-dev.txt
  src/__init__.py
Labels: enhancement

#7 [TWEAK] Extracted bandit from pre-commit
  poetry.lock
  pyproject.toml
  requirements-dev.txt
Labels: enhancement

#9 [FEATURE] : Reworked linter outputs
  .gitignore
  poetry.lock
  pyproject.toml
Labels: enhancement, question

#11 [FEATURE] Sphinx
  docs/Makefile
  docs/make.bat
  docs/source/_static/keepit
  docs/source/_templates/keepit
  docs/source/conf.py
  docs/source/index.rst
  poetry.lock
  pyproject.toml
  requirements-dev.txt
Labels: documentation, enhancement
